# Trydan to MQTT Bridge Configuration
# This file contains all configuration settings for the bridge application

# Trydan EV Charger Configuration
trydan:
  # IP address or hostname of the Trydan device
  host: "192.168.1.100"

# MQTT Broker Configuration
mqtt:
  # MQTT broker hostname or IP address
  host: "localhost"
  # MQTT broker port (default: 1883, SSL: 8883)
  port: 1883
  # MQTT client ID (must be unique)
  client_id: "trydan2mqtt"
  # Topic prefix for all published messages
  topic_prefix: "trydan"
  # Keep alive interval in seconds
  keepalive: 60
  
  # Authentication (optional)
  username: "mqtt_user"
  password: "mqtt_password"
  
  # TLS/SSL Configuration (optional)
  tls:
    enabled: false
    ca_certs: "/path/to/ca.crt"
    certfile: "/path/to/client.crt"
    keyfile: "/path/to/client.key"

# Bridge Configuration
bridge:
  # Data polling interval in seconds
  poll_interval: 30
  # Retry attempts for failed connections
  retry_attempts: 5
  # Retry delay in seconds
  retry_delay: 10

# Logging Configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # Maximum log file size in MB
  max_file_size: 10
  # Number of backup log files to keep
  backup_count: 5